paths:
  /api/products/:
    get:
      summary: Se muestran todos los productos disponibles para la compra.
      tags:
        - Products
      responses:
        '200':
          description: Los productos fueron traidos con éxito.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '500':
          description: Error interno del servidor.
    post:
      summary: Aquellos usuarios con rol de "administrador" y/o "premium" pueden agregar productos nuevos.
      tags:
        - Products
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/requestBodies/updateProduct'
      responses:
        '200':
          description: El producto fue agregado correctamente.
        '400':
          description: No se puede agregar el producto debido a la falta de datos del mismo.
        '500':
          description: Error interno del servidor.
  /api/products/id/{pid}:
    get:
      summary: Se muestra el producto con ID igual a la ingresada en la ruta.
      tags:
        - Products
      parameters:
        - name: pid
          in: path
          required: true
          description: El ID del producto que se desea traer.
          schema:
            type: string
      responses:
        '200':
          description: El producto ha sido traido con éxito.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: No se ha encontrado el producto con ese ID.
        '500':
          description: Error interno del servidor.
  /api/products/name/{title}:
    put:
      summary: Aquellos usuarios con rol de "administrador" pueden actualizar los datos de un producto en particular. En caso de ser rol "premium", puede actualizar solamente un producto suyo.
      tags:
        - Products
      parameters:
        - name: title
          in: path
          required: true
          description: El nombre del producto que se desea actualizar.
          schema:
            type: string
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: '#/components/requestBodies/updateProduct'
      responses:
        '200':
          description: El producto fue actualizado con éxito.
        '400':
          description: No se ha encontrado el producto con ese ID.
        '401':
          description: No se puede actualizar el producto debido a la falta de datos del mismo.
        '500':
          description: Error interno del servidor.
    delete:
      summary: Aquellos usuarios con rol de "administrador" pueden eliminar un producto en particular. En caso de ser rol "premium", puede eliminar solamente un producto suyo.
      tags:
        - Products
      parameters:
        - name: title
          in: path
          required: true
          description: El nombre del producto que se desea eliminar.
          schema:
            type: string
      responses:
        '200':
          description: El producto fue eliminado con éxito.
        '400':
          description: No se ha encontrado el producto con ese ID.
        '401':
          description: No se puede eliminar el producto debido a la falta de permisos del usuario.
        '500':
          description: Error interno del servidor.

components:
  schemas:
    Product:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID autogenerada por MongoDB.
        title:
          type: String
          description: Nombre del producto.
        description:
          type: String
          description: Descripción del producto.
        price:
          type: Number
          description: Precio del producto.
        department:
          type: String
          description: Categoría del producto.
        href:
          type: String
          description: Enlace de imagen del producto.
        code:
          type: String
          description: Código único del producto.
        stock:
          type: Number
          description: Stock disponible del producto.
        owner:
          type: String
          description: En caso de haber sido creado por un usuario "premium", muestra el correo del usuario.
        status:
          type: Boolean
          description: Status del producto.
      example:
        _id: ObjectId("64a71475d4f30034f93a0f4d")
        title: Hormigon Raton
        description: The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients
        price: 462
        department: Cine
        href: Sin imagen
        code: 1pb33
        stock: 6
        owner: admin
        status: true
  requestBodies:
    updateProduct:
      type: object
      properties:
        title:
          type: String
          description: Nombre del producto.
        description:
          type: String
          description: Descripción del producto.
        price:
          type: Number
          description: Precio del producto.
        department:
          type: String
          description: Categoría del producto.
        href:
          type: String
          description: Enlace de imagen del producto.
        code:
          type: String
          description: Código único del producto.
        stock:
          type: Number
          description: Stock disponible del producto.
        owner:
          type: String
          description: En caso de haber sido creado por un usuario "premium", muestra el correo del usuario.
        status:
          type: Boolean
          description: Status del producto.
      example:
        title: Hormigon Raton
        description: The beautiful range of Apple Naturalé that has an exciting mix of natural ingredients. With the Goodness of 100% Natural Ingredients
        price: 462
        department: Cine
        href: Sin imagen
        code: 1pb33
        stock: 6
        owner: admin
        status: true